<?php

namespace Database\Seeders;

use App\Models\Client;
use App\Models\Policy;
use App\Models\Sede;
use Illuminate\Database\Seeder;

class KfmSampleSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Crear las dos Oficinas oficiales de KFM (Central y NEX)
        $oficinaCentral = Sede::firstOrCreate(
            ['slug' => 'central'],
            [
                'name' => 'Oficina Central (Pueblo)',
                'address' => 'Plaza Triunfo de la Virgen del Rosario Coronada, 7, Bajo (11520 Rota)',
                'phone' => '+34 956 84 00 50',
                'color' => '#145a78', // KFM Navy
            ]
        );

        $oficinaNEX = Sede::firstOrCreate(
            ['slug' => 'nex'],
            [
                'name' => 'Oficina NEX (Base Naval)',
                'address' => 'NEX (Navy Exchange) - Edificio Comercial NAVSTA Rota',
                'phone' => '+34 956 81 16 16',
                'color' => '#00739c', // KFM Cerulean
            ]
        );

        // Agentes activas (Kerry, Coral, Conchi, Chari)
        $agentes = ['Kerry', 'Coral', 'Conchi', 'Chari'];

        // 2. Extraer exactamente los 20 primeros clientes reales del Excel con sus datos ampliados
        $sampleData = [
            [
                'doc_identidad' => '582811386',
                'nombre' => 'JONATHAN',
                'apellido' => 'NEGRON',
                'nombre_familiar' => '',
                'agente' => 'Kerry',
                'dob' => '28/09/79',
                'telefono_movil' => '628-561129',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'JONATHAN.NEGRON.0311@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 BOX 7596 – 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Personal US Navy en base.',
                'policies' => [
                    [
                        'numero_poliza' => '1661462',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'HONDA',
                        'modelo' => 'CIVIC 1.5I S ELEGANC',
                        'matricula' => '0680 JCL',
                        'prima' => '406,05 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '13/02/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ]
                ]
            ],
            [
                'doc_identidad' => 'Y1979608N',
                'nombre' => 'GLENN',
                'apellido' => 'FERGUSON',
                'nombre_familiar' => 'Mary Ferguson (Esposa)',
                'agente' => 'Coral',
                'dob' => '08/04/56',
                'telefono_movil' => '638-932479',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'glennferguson@aol.com',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 BOX 183 1R - 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => '',
                'policies' => [
                    [
                        'numero_poliza' => '1649692',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'HONDA',
                        'modelo' => 'CB 750 K',
                        'matricula' => '5550 HBG',
                        'prima' => '305,38 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '23/12/2026',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ],
                    [
                        'numero_poliza' => '1649692-B',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'BMW',
                        'modelo' => 'R 1200',
                        'matricula' => '8088 GFZ',
                        'prima' => '280,70 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '27/02/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ]
                ]
            ],
            [
                'doc_identidad' => 'Y1483288D',
                'nombre' => 'WALID',
                'apellido' => 'ABUHAIDAR',
                'nombre_familiar' => 'Ignacio Molinario (Tomador)',
                'agente' => 'Conchi',
                'dob' => '16/05/80',
                'telefono_movil' => '699-193082',
                'telefono_fijo' => '003-76-694578',
                'email_trabajo' => '',
                'email_personal' => 'WALIDMABUHAIDAR@GMAIL.COM',
                'direccion_local' => 'C/ CARRER BOTELLA, 5 – 08007 BARCELONA',
                'direccion_base' => '',
                'sede_id' => $oficinaCentral->id,
                'observaciones' => 'Contacto preferente por WhatsApp.',
                'policies' => [
                    [
                        'numero_poliza' => '1649862',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '87',
                        'aseguradora' => 'Liberty Seguros',
                        'marca' => 'TRIUMPH',
                        'modelo' => 'BONNEVILLE 900 BLA',
                        'matricula' => '2325 FWS',
                        'prima' => '409,97 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '04/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ],
                    [
                        'numero_poliza' => '1658557',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'SYM',
                        'modelo' => 'MIO 50 ORIGINAL',
                        'matricula' => 'C5338 BVK',
                        'prima' => '240,01 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '01/10/2026',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ]
                ]
            ],
            [
                'doc_identidad' => '146600105',
                'nombre' => 'EILEEN',
                'apellido' => 'KLESS',
                'nombre_familiar' => '',
                'agente' => 'Kerry',
                'dob' => '21/04/61',
                'telefono_movil' => '685-693455',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'EKONTHEROCK@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 BOX 8233 - 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => '',
                'policies' => [
                    [
                        'numero_poliza' => '1661912',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'BMW',
                        'modelo' => 'SERIE 1 E81 116D 3P',
                        'matricula' => '2534 GYK',
                        'prima' => '677,30 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '08/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ]
                ]
            ],
            [
                'doc_identidad' => '224907957',
                'nombre' => 'JEFFREY',
                'apellido' => 'RANCK',
                'nombre_familiar' => 'Edward Llamas (Cesionario)',
                'agente' => 'Coral',
                'dob' => '03/04/61',
                'telefono_movil' => '628-143959',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'JEFFREY.RANCK@YAHOO.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC-819 – BOX 29 – 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Vehículo transferido anteriormente.',
                'policies' => [
                    [
                        'numero_poliza' => '1650058',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'FORD',
                        'modelo' => 'FOCUS 2,0 TREND 4P',
                        'matricula' => '40069',
                        'prima' => '413,67 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '14/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ],
                    [
                        'numero_poliza' => '904959',
                        'ramo' => 'Hogar',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'tipo_vivienda' => 'UNIF NO ADOSADA',
                        'direccion_riesgo' => 'Rota Naval Housing',
                        'prima' => '180,09 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '22/12/2026',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ]
                ]
            ],
            [
                'doc_identidad' => '557912786',
                'nombre' => 'RALPH',
                'apellido' => 'SALAS',
                'nombre_familiar' => 'Katrina Salas (Esposa)',
                'agente' => 'Kerry',
                'dob' => '03/06/84',
                'telefono_movil' => '620-112233',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'RSALAS84@HOTMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'CL PSC 819 – BOX 2288 - 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Esposo de Katrina Salas.',
                'policies' => [
                    [
                        'numero_poliza' => '1650079',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'HONDA',
                        'modelo' => 'CR-V 2.4 I-VTEC 188',
                        'matricula' => 'WWV 6060',
                        'prima' => '678,41 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '15/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ]
                ]
            ],
            [
                'doc_identidad' => '519650581',
                'nombre' => 'KATRINA',
                'apellido' => 'SALAS',
                'nombre_familiar' => 'Ralph Salas (Esposo)',
                'agente' => 'Kerry',
                'dob' => '16/08/85',
                'telefono_movil' => '620-112234',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'KATRINA.SALAS@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'CL PSC -819 BOX 2288 - 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => '',
                'policies' => [
                    [
                        'numero_poliza' => '1651228',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'SUZUKI',
                        'modelo' => 'SAMURAI 63',
                        'matricula' => 'CO 7627 T',
                        'prima' => '345,80 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '19/02/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ]
                ]
            ],
            [
                'doc_identidad' => '490986002',
                'nombre' => 'LAURA',
                'apellido' => 'ARRINGTON',
                'nombre_familiar' => '',
                'agente' => 'Conchi',
                'dob' => '28/02/88',
                'telefono_movil' => '684-057982',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'lla06@hotmail.com',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 62 – BOX 6937 - 41530 MORON DE LA FRA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Destacamento Morón / Rota.',
                'policies' => [
                    [
                        'numero_poliza' => '1661735',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'FIAT',
                        'modelo' => 'BRAVO 1,6 SX 3P',
                        'matricula' => 'SE 7993 CW',
                        'prima' => '336,61 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '15/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ]
                ]
            ],
            [
                'doc_identidad' => '231949105',
                'nombre' => 'CINTHIA',
                'apellido' => 'MOGAN',
                'nombre_familiar' => '',
                'agente' => 'Coral',
                'dob' => '19/02/57',
                'telefono_movil' => '642-998877',
                'telefono_fijo' => '',
                'email_trabajo' => 'cynthia.mogan2@eu.navy.mil',
                'email_personal' => 'CMOGAN@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 - BOX 2809 - 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'NAVSTA Rota EU Navy.',
                'policies' => [
                    [
                        'numero_poliza' => '1661693',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'ACURA',
                        'modelo' => 'TSX 2.4 4P',
                        'matricula' => '7064 JBZ',
                        'prima' => '797,05 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '18/12/2026',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ]
                ]
            ],
            [
                'doc_identidad' => '461783410',
                'nombre' => 'STEPHEN',
                'apellido' => 'PAYNE',
                'nombre_familiar' => '',
                'agente' => 'Kerry',
                'dob' => '28/03/56',
                'telefono_movil' => '655-443322',
                'telefono_fijo' => '956-824185',
                'email_trabajo' => 'STEPHEN.PAYNE@EU.DODEA.EDU',
                'email_personal' => 'SPAYNE56@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'CL PSC 819 – BOX 19 - 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Profesor en DODEA High School Base Rota.',
                'policies' => [
                    [
                        'numero_poliza' => '1650108',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'BMW',
                        'modelo' => 'SERIE 3 328 I 4P',
                        'matricula' => 'CA 8974 BF',
                        'prima' => '209,83 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '17/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ]
                ]
            ],
            [
                'doc_identidad' => '350781457',
                'nombre' => 'JEREMY',
                'apellido' => 'DUNN',
                'nombre_familiar' => '',
                'agente' => 'Coral',
                'dob' => '19/04/78',
                'telefono_movil' => '608-157000',
                'telefono_fijo' => '956-822850',
                'email_trabajo' => 'JEREMY.DUNN@EU.NAVY.MIL',
                'email_personal' => 'JDUNN78@HOTMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 - BOX 2816 – 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => '',
                'policies' => [
                    [
                        'numero_poliza' => '1661849',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'CHEVROLET',
                        'modelo' => 'PICK UP 2,8 S',
                        'matricula' => 'S/M',
                        'prima' => '436,66 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '21/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ]
                ]
            ],
            [
                'doc_identidad' => '502239457',
                'nombre' => 'CHARLES',
                'apellido' => 'HAMPTON',
                'nombre_familiar' => '',
                'agente' => 'Conchi',
                'dob' => '14/05/69',
                'telefono_movil' => '677-123456',
                'telefono_fijo' => '',
                'email_trabajo' => 'charles.hampton@ddg75.navy.mil',
                'email_personal' => 'CHAMPTON@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG USS DONALD COOK DDG 75 – 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Destructor USS Donald Cook DDG 75.',
                'policies' => [
                    [
                        'numero_poliza' => '1662014',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'PIAGGIO',
                        'modelo' => 'VESPA 50 LX',
                        'matricula' => 'C 9733 BTH',
                        'prima' => '266,82 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '22/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ]
                ]
            ],
            [
                'doc_identidad' => '548810324',
                'nombre' => 'SEAN',
                'apellido' => 'BOLTON',
                'nombre_familiar' => 'Mª Jesus Cano (Cesionaria Panda)',
                'agente' => 'Kerry',
                'dob' => '03/12/69',
                'telefono_movil' => '608-247118',
                'telefono_fijo' => '956-821302',
                'email_trabajo' => 'SEAN.BOLTON@EU.NAVY.MIL',
                'email_personal' => 'SBOLTON69@YAHOO.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 – BOX 9 – 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Cliente consolidado con múltiples vehículos y hogar.',
                'policies' => [
                    [
                        'numero_poliza' => '1661891',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'TOYOTA',
                        'modelo' => '4 RUNNER 2,4 TD 5P',
                        'matricula' => '3926 HJN',
                        'prima' => '440,79 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '22/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ],
                    [
                        'numero_poliza' => '1654191',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'FIAT',
                        'modelo' => 'PANDA 1.2 DYNAMIC',
                        'matricula' => '1609 GHM',
                        'prima' => '311,81 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '04/05/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ],
                    [
                        'numero_poliza' => '906917',
                        'ramo' => 'Hogar',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'tipo_vivienda' => 'UNIF ADOSADA',
                        'direccion_riesgo' => 'Rota Naval Housing',
                        'prima' => '340,79 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '27/05/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ]
                ]
            ],
            [
                'doc_identidad' => '559170851',
                'nombre' => 'EUGENE',
                'apellido' => 'CORPUS',
                'nombre_familiar' => '',
                'agente' => 'Coral',
                'dob' => '27/02/64',
                'telefono_movil' => '642-482508',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'CORPUZEUGENE@HOTMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 BOX 49 - 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Tiene Audi Q5 y BMW Serie 3.',
                'policies' => [
                    [
                        'numero_poliza' => '1652589',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'AUDI',
                        'modelo' => 'Q5 2.0 TDI 177 AMBIT 5P',
                        'matricula' => '5716 HWM',
                        'prima' => '813,35 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '01/04/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ],
                    [
                        'numero_poliza' => '1688929',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'BMW',
                        'modelo' => 'SERIE 3 318DA 5P',
                        'matricula' => '8264 JVH',
                        'prima' => '721,97 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '02/12/2026',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ]
                ]
            ],
            [
                'doc_identidad' => '545067926',
                'nombre' => 'ROBIN',
                'apellido' => 'HUDSON',
                'nombre_familiar' => '',
                'agente' => 'Kerry',
                'dob' => '31/05/55',
                'telefono_movil' => '648-285103',
                'telefono_fijo' => '956-823232',
                'email_trabajo' => 'ROBIN.HUDSON@EU.NAVY.MIL',
                'email_personal' => 'RHUDSON55@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG PSC 819 - BOX 57 - 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => '',
                'policies' => [
                    [
                        'numero_poliza' => '1650325',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'BMW',
                        'modelo' => 'X1 XDRIVE 28 I 5P',
                        'matricula' => '0512 HVK',
                        'prima' => '784,97 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '23/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Kerry',
                    ]
                ]
            ],
            [
                'doc_identidad' => '251678957',
                'nombre' => 'DEON',
                'apellido' => 'DRAYTON',
                'nombre_familiar' => '',
                'agente' => 'Coral',
                'dob' => '22/01/84',
                'telefono_movil' => '611-998811',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'DDRAYTON@GMAIL.COM',
                'direccion_local' => '',
                'direccion_base' => 'LG USS ROSS DDG 71 – 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Destructor USS Ross DDG 71.',
                'policies' => [
                    [
                        'numero_poliza' => '1662050',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'MERCEDES',
                        'modelo' => 'CLX 200',
                        'matricula' => '9881 BVY',
                        'prima' => '413,05 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '16/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ]
                ]
            ],
            [
                'doc_identidad' => '563496225',
                'nombre' => 'FREDERICK',
                'apellido' => 'WOODS',
                'nombre_familiar' => '',
                'agente' => 'Conchi',
                'dob' => '30/11/71',
                'telefono_movil' => '626-912241',
                'telefono_fijo' => '956-852967',
                'email_trabajo' => 'FWOODS@NCI.NAVY.MIL',
                'email_personal' => 'FWOODS71@HOTMAIL.COM',
                'direccion_local' => 'C/ MANAGUA 3 - 11500 EL PUERTO DE SANTA MARIA',
                'direccion_base' => 'LG PSC 819 BOX 2827 – 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Vive en El Puerto de Santa María.',
                'policies' => [
                    [
                        'numero_poliza' => '1662504',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'HONDA',
                        'modelo' => 'ODYSSEY 3.5 EX-L 248',
                        'matricula' => 'S/M',
                        'prima' => '731,13 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '26/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ],
                    [
                        'numero_poliza' => '909368',
                        'ramo' => 'Hogar',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'tipo_vivienda' => 'UNIF NO ADOSADA',
                        'direccion_riesgo' => 'C/ Managua 3, El Puerto',
                        'prima' => '266,64 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '03/02/2027',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ]
                ]
            ],
            [
                'doc_identidad' => '52311676Q',
                'nombre' => 'MERCEDES',
                'apellido' => 'MARTINEZ IZQUIERDO',
                'nombre_familiar' => '',
                'agente' => 'Conchi',
                'dob' => '16/07/68',
                'telefono_movil' => '620-974493',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'MERCEDESMIZQUIERDO@GMAIL.COM',
                'direccion_local' => 'C/ SANTISIMO CRISTO YACIENTE, 1 – 11520 ROTA',
                'direccion_base' => '',
                'sede_id' => $oficinaCentral->id,
                'observaciones' => 'Cliente local de Rota.',
                'policies' => [
                    [
                        'numero_poliza' => '1650744',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'PEUGEOT',
                        'modelo' => '207 1.4 HDI',
                        'matricula' => '6579 HVM',
                        'prima' => '320,00 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '05/04/2027',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ]
                ]
            ],
            [
                'doc_identidad' => '52314099R',
                'nombre' => 'MANUEL',
                'apellido' => 'GOMEZ GARCIA',
                'nombre_familiar' => 'Madre (Contacto)',
                'agente' => 'Conchi',
                'dob' => '24/06/74',
                'telefono_movil' => '637-565158',
                'telefono_fijo' => '856-112247',
                'email_trabajo' => '',
                'email_personal' => 'MANUEL.GOMEZ.ROTA@GMAIL.COM',
                'direccion_local' => 'AVD MARIA AUXILIADORA PORTAL 43 3º D - 11520 ROTA',
                'direccion_base' => '',
                'sede_id' => $oficinaCentral->id,
                'observaciones' => 'Cliente local del pueblo de Rota.',
                'policies' => [
                    [
                        'numero_poliza' => '1684640',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'OPEL',
                        'modelo' => 'ASTRA 1.6 16V CONFORT',
                        'matricula' => 'CA 8121 BM',
                        'prima' => '407,33 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '27/12/2026',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ],
                    [
                        'numero_poliza' => '1734608',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'OPEL',
                        'modelo' => 'ZAFIRA 1.9 CDTI COSMO',
                        'matricula' => '2355 FCJ',
                        'prima' => '455,55 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '21/01/2027',
                        'estado' => 'Activo',
                        'agente' => 'Conchi',
                    ]
                ]
            ],
            [
                'doc_identidad' => '572330113',
                'nombre' => 'CASEY',
                'apellido' => 'BRESSEM',
                'nombre_familiar' => 'Michael Jose (Familiar)',
                'agente' => 'Coral',
                'dob' => '14/02/63',
                'telefono_movil' => '608-690211',
                'telefono_fijo' => '',
                'email_trabajo' => '',
                'email_personal' => 'MICHAEL_JOSE5@MSN.COM',
                'direccion_local' => 'AVDA ALVARO DOMEQ 44 - ROTA',
                'direccion_base' => 'LG PSC 819 - BOX 2487 - 11530 ROTA',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Pólizas de coche, scooter y hogar.',
                'policies' => [
                    [
                        'numero_poliza' => '1770264',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'BMW',
                        'modelo' => 'X1 E84',
                        'matricula' => '8534 LZC',
                        'prima' => '653,43 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '14/07/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ],
                    [
                        'numero_poliza' => '1667678',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'PIAGGIO',
                        'modelo' => 'VESPA ZIP 50 2T',
                        'matricula' => 'C 0240 BVW',
                        'prima' => '251,62 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '06/06/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ],
                    [
                        'numero_poliza' => '937530',
                        'ramo' => 'Hogar',
                        'codigo_aseguradora' => '81',
                        'aseguradora' => 'Patria Hispana',
                        'tipo_vivienda' => 'UNIF NO ADOSADA',
                        'direccion_riesgo' => 'Avda Alvaro Domeq 44, Rota',
                        'prima' => '145,38 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '25/05/2027',
                        'estado' => 'Activo',
                        'agente' => 'Coral',
                    ]
                ]
            ],
            [
                'doc_identidad' => '549218471',
                'nombre' => 'DAVID ALEXANDER',
                'apellido' => 'MILLER',
                'nombre_familiar' => 'Emily Sarah Johnson (Cesionaria)',
                'agente' => 'Chari',
                'dob' => '14/06/1988',
                'telefono_movil' => '671-234567',
                'telefono_fijo' => '',
                'email_trabajo' => 'david.miller@eu.navy.mil',
                'email_personal' => 'david.miller.usn@gmail.com',
                'direccion_local' => 'C/ SAN JUAN DE PUERTO RICO 12 – 11520 ROTA',
                'direccion_base' => 'LG PSC 819 BOX 4120 - 11530 ROTA NAVAL',
                'sede_id' => $oficinaNEX->id,
                'observaciones' => 'Caso demostración: Transferencia POV / Cesión de póliza en Gestoría Bahía & Naval (Oficina NEX - Chari).',
                'policies' => [
                    [
                        'numero_poliza' => '1842910',
                        'ramo' => 'Vehiculo',
                        'codigo_aseguradora' => '04',
                        'aseguradora' => 'Patria Hispana',
                        'marca' => 'FORD',
                        'modelo' => 'FOCUS TITANIUM 1.5 ECOBOOST 5P',
                        'matricula' => '5931LKP',
                        'vin' => '1FADP5CU3DL298491',
                        'prima' => '642,50 €',
                        'tipo_facturacion' => 'Annual',
                        'balance' => 'Paid Full',
                        'liquidacion' => 'Liquidado',
                        'fecha_vencimiento' => '15/11/2026',
                        'estado' => 'Activo',
                        'agente' => 'Chari',
                    ]
                ]
            ],
        ];

        foreach ($sampleData as $data) {
            $policies = $data['policies'] ?? [];
            unset($data['policies']);

            $client = Client::create($data);

            foreach ($policies as $polData) {
                $polData['client_id'] = $client->id;
                $polData['sede_id'] = $client->sede_id;
                Policy::create($polData);
            }
        }
    }
}
